accounts/urls.py
from django.urls import path, include, reverse_lazy, re_path
from . import views
from django.contrib.auth import views as auth_views

app_name = "accounts"

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', auth_views.LoginView.as_view(
        template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(
        template_name='accounts/logout.html'), name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('change-password/', auth_views.PasswordChangeView.as_view(
        template_name='accounts/change_password.html',
        success_url=reverse_lazy('accounts:change_password_done')), name='change_password'),
    path('change-password/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='accounts/password_change_done.html'),
        name='change_password_done'),

    path('reset-password/', auth_views.PasswordResetView.as_view(
        template_name='accounts/reset_password.html',
        email_template_name='accounts/reset_password_email.html',
        success_url=reverse_lazy('accounts:password_reset_done')),
        name='reset_password'),

    path('reset-password/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/reset_password_done.html'),
        name='password_reset_done'),

    path('reset-password/confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('accounts:password_reset_complete'),
        template_name='accounts/reset_password_confirm.html'),
        name='password_reset_confirm'),

    path('reset-password/complete/',
        auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/reset_password_complete.html'),
        name='password_reset_complete'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)


class MyUserManager(BaseUserManager):

    def create_user(self, email, first_name, last_name, talent=None,
                    password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError("Users must have and email Address")
        if not password:
            raise ValueError("Users must have a password")
        if not first_name:
            raise ValueError("User must have a first name")
        if not last_name:
            raise ValueError("User must have a last name")

        user = self.model(
            email = self.normalize_email(email),
            first_name = first_name,
            last_name = last_name,
            talent = talent,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, talent=None, password=None):

        user = self.create_user(
            email,
            first_name = first_name,
            last_name = last_name,
            talent = talent,
            password = password,
        )

        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    email = models.EmailField(max_length=255,unique=True)
    first_name  = models.CharField(max_length=255, blank=True, null=True)
    last_name   = models.CharField(max_length=255, blank=True, null=True)
    talent      = models.CharField(max_length=255, blank=True, null=True)
    is_active      = models.BooleanField(default=True)
    #is_staff       = models.BooleanField(default=False)
    is_admin       = models.BooleanField(default=False)
    timestamp   = models.DateTimeField(auto_now_add=True)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin


    # def create_staffuser(self, email, first_name, last_name,
    #                      talent=None, password=None):
    #     user = self.create_user(
    #         email = self.normalize_email(email),
    #         first_name = first_name,
    #         last_name = last_name,
    #         talent = talent,
    #         password=password
    #     )
    #     user.is_staff = True
    #     user.save(using=self.db)
    #     return user

accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from accounts.models import MyUser

class UserAdminCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = MyUser
        fields = ('email', 'first_name', 'last_name', 'talent',)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = MyUser.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("email is taken")
        return email

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = MyUser
        fields = ('email', 'first_name', 'last_name', 'talent', 'password',
                  'is_active', 'is_admin')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

class RegisterationForm(forms.ModelForm):

    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = MyUser
        fields = ('first_name',
                  'last_name',
                  'email',
                  'talent',
                  'password1',
                  'password2',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def clean_talent(self):
        talent = self.cleaned_data.get("talent")
        if talent == None:
            raise forms.ValidationError("Talent is required")
        return talent

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(RegisterationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

accounts/views.py
from django.shortcuts import render, redirect
from accounts.forms import RegisterationForm
from django.views.generic import CreateView, FormView
from accounts.models import MyUser
from django.urls import reverse

def home(request):
    return render(request, 'accounts/home.html')

def register(request):
    if request.method == 'POST':
        form = RegisterationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:home'))
    else:
        form = RegisterationForm()

    args = {'form': form}
    return render(request, 'accounts/register_form.html', args)

def profile(request):
    args = {'user': request.user}
    return render(request, 'accounts/profile.html', args)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block head %}
  <title>Profile Edit</title>
{% endblock %}

{% block body %}
  <div class="container">
    <form method='post'>
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
{% endblock %}

accounts/templates/accounts/home.html
{% extends 'base.html' %}

{% block head %}
  <title>Home</title>
{% endblock %}
{% block body %}
  <div class="container">
    <h1>From the home page.</h1>
  </div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block head %}
  <title>Log In</title>
{% endblock %}

{% block body %}
  <div class="container">
    <p>You can log in here!</p>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Login</button>
    </form>
  </div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block head %}
  <title>LogOut</title>
{% endblock %}

{% block body %}
  <div class="container">
    <h1>Logged Out</h1>
    <p>You have been logged out.</p>
  </div>
{% endblock %}

accounts/templates/accounts/password_change_done.html
{% extends 'base.html' %}

{% block head %}
  <title>Password change successful</title>
{% endblock %}

{% block body %}
  <div class="container">
    <h1>Password change successful</h1>
    <p>Your password was changed.</p>
  </div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block head %}
  <title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
  {{ user.talent }}
</div>
{% endblock %}

accounts/templates/accounts/register_form.html
{% extends 'base.html' %}
{% block head %}
  <title>Log Out</title>
{% endblock %}

{% block body %}
  <div class="container">
    <p>You can register in here!</p>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Register</button>
    </form>
  </div>
{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block head %}
  <title>Password Reset</title>
{% endblock %}

{% block body %}
<div class="container">
  <h1>Password Reset</h1>
  <p>
    Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
  </p>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Reset Password</button>
  </form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_complete.html
{% extends 'base.html' %}

{% block head %}
  <title>Password Reset Complete</title>
{% endblock %}

{% block body %}
<div class="container">
  <h1>Password Reset Complete</h1>
  <p>
    Your password has been set. You may go ahead and log in now.
  </p>
  <a href="/accounts/login">Login</a>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
  <h1>Enter New Password</h1>
  <p>

  </p>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Reset Password</button>
  </form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_done.html
{% extends 'base.html' %}

{% block head %}
  <title>Password Reset Sent</title>
{% endblock %}

{% block body %}
<div class="container">
  <h1>Password Reset Sent</h1>
  <p>
    We've emailed you instructions for setting your password,
    if an account exists with the email you entered. You should receive them shortly.

    If you don't receive an email, please make sure you've entered the address
    you registered with, and check your spam folder.
  </p>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}